### ISSUE TITLE
가나다순 자동완성 관련하여 문의입니다.

### ISSUE THREAD

**Issue by cepiloth** [libreoffice-kr/autocorr_kr#18]
가나다 오름 차순으로 단어를 입력해야하는데
자동으로 자동 완성 되는 방법이 있을까요?

sheet 문서에 넣고 가나다 순으로 정렬이 되긴하네요.
![image](https://user-images.githubusercontent.com/16272811/95151273-368b9080-07c5-11eb-8a9f-ec168409b407.png)

**Comment by studioego** [comment]
자동으로 완성되는 건 없지만, 이걸 CI로 돌릴 수 있게 고민은 해보겠습니다.
지금은 엑셀이나 LibreOffice Calc로 오름차순으로 정렬하는 거밖에 생각이 나지 않군요. 좋은 의견 있으면 공유 부탁드립니다

(그럼 Github의  CI도구공부를 해야할듯한)

**Comment by cepiloth** [comment]
XML Data 를 읽고 C# LINQ 기능을 이용해서  정렬을 하는 식으로 샘플 프로그램을 제작해 봐야겠습니다.
